
--
-- Table DOSSIER
--

use TEST;

DROP TABLE IF EXISTS DOSSIERS;

CREATE TABLE DOSSIERS  (
	ID int NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'Unique ID',
	DAT_CRE timestamp NOT NULL default current_timestamp COMMENT 'Date creation',
	DOSSIER INT NOT NULL COMMENT 'No de Dossier',
	BANQUE VARCHAR(5) NOT NULL COMMENT 'Code Banque',
	QTE INT NOT NULL DEFAULT 0 COMMENT 'Qte Dossier',
	NBFOLIO INT NOT NULL DEFAULT 0 COMMENT 'Nb feuillet',
	STATUT INT NOT NULL DEFAULT 0 COMMENT 'Statut du dossier',
	NB_OP INT NOT NULL DEFAULT 0 COMMENT 'Nbre operations'
	);

